"""empty message

Revision ID: 80facef57376
Revises: 00a3cc42ef97
Create Date: 2026-09-22 14:43:33.982918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80facef57376'
down_revision = '00a3cc42ef97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    # ### end Alembic commands ###
